apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: odf-node-recovery-operator
    app.kubernetes.io/instance: manager-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: odf-node-recovery-operator
  name: odf-node-recovery-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: odf-node-recovery-operator-manager-role
subjects:
- kind: ServiceAccount
  name: odf-node-recovery-operator-controller-manager
  namespace: odf-node-recovery-operator-system
