apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "odf.openshift.io/v1alpha1",
          "kind": "NodeRecovery",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "odf-node-recovery-operator",
              "app.kubernetes.io/instance": "noderecovery-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "noderecovery",
              "app.kubernetes.io/part-of": "odf-node-recovery-operator"
            },
            "name": "noderecovery-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    createdAt: "2024-10-08T13:16:09Z"
    operators.operatorframework.io/builder: operator-sdk-v1.37.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: odf-node-recovery-operator.v0.0.1
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: NodeRecovery
      name: noderecoveries.odf.openshift.io
      version: v1alpha1
  description: fdsa
  displayName: operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: odf-node-recovery-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: odf-node-recovery-operator
          control-plane: controller-manager
        name: odf-node-recovery-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.15.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: controller:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: odf-recovery
              terminationGracePeriodSeconds: 10
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - fsda
  links:
  - name: Odf Node Recovery Operator
    url: https://odf-node-recovery-operator.domain
  maturity: alpha
  provider:
    name: fds
    url: fdsa
  version: 0.0.1
