# Patch for Prometheus ServiceMonitor to enable secure TLS configuration
# using certificates managed by cert-manager
- op: replace
  path: /spec/endpoints/0/tlsConfig
  value:
    # SERVICE_NAME and SERVICE_NAMESPACE will be substituted by kustomize
    serverName: odf-node-recovery-operator-controller-manager-metrics-service
    insecureSkipVerify: false
    ca:
      secret:
        name: odf-node-recovery-operator-metrics-reader
        key: service-ca.crt
