apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: odf-node-recovery-operator-metrics-reader
  name: metrics-reader
  namespace: system
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-reader
  namespace: system