---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ocs.openshift.io
  resources:
  - ocsinitializations
  verbs:
  - get
- apiGroups:
  - odf.openshift.io
  resources:
  - noderecoveries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - odf.openshift.io
  resources:
  - noderecoveries/finalizers
  verbs:
  - update
- apiGroups:
  - odf.openshift.io
  resources:
  - noderecoveries/status
  verbs:
  - get
  - patch
  - update
