apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: odf-node-recovery-operator.v0.0.0
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: ODF Node Recovery
  displayName: operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - odf, node recovery
  links:
  - name: Odf Node Recovery Operator
    url: https://odf-node-recovery-operator.domain
  maturity: alpha
  minKubeVersion: 1.25.0
  provider:
    name: Red Hat
    url: www.redhat.com
  version: 0.0.0
