/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	apiv1alpha1 "github.com/jordigilh/odf-node-recovery-operator/api/v1alpha1"
	versioned "github.com/jordigilh/odf-node-recovery-operator/client/clientset/versioned"
	internalinterfaces "github.com/jordigilh/odf-node-recovery-operator/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/jordigilh/odf-node-recovery-operator/client/listers/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// NodeRecoveryInformer provides access to a shared informer and lister for
// NodeRecoveries.
type NodeRecoveryInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.NodeRecoveryLister
}

type nodeRecoveryInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewNodeRecoveryInformer constructs a new informer for NodeRecovery type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNodeRecoveryInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredNodeRecoveryInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredNodeRecoveryInformer constructs a new informer for NodeRecovery type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredNodeRecoveryInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiV1alpha1().NodeRecoveries().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiV1alpha1().NodeRecoveries().Watch(context.TODO(), options)
			},
		},
		&apiv1alpha1.NodeRecovery{},
		resyncPeriod,
		indexers,
	)
}

func (f *nodeRecoveryInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredNodeRecoveryInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *nodeRecoveryInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiv1alpha1.NodeRecovery{}, f.defaultInformer)
}

func (f *nodeRecoveryInformer) Lister() v1alpha1.NodeRecoveryLister {
	return v1alpha1.NewNodeRecoveryLister(f.Informer().GetIndexer())
}
