name: Sanity checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Make build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the manifest
      run: |
        make build

  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run unit tests
      run: |
        make test