on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      coverage:  ${{ steps.ginkgo-tests.outputs.coverage }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - run: go mod tidy && git diff --exit-code go.mod go.sum
      - run: go vet ./...

      - name: Run Ginkgo tests with coverage
        id: ginkgo-tests
        run: |
          make test